# configuration.nix — host configuration (EXAMPLE).
# ════════════════════════════════════════════════════════════════════════════
# Minimal host setup for a dedicated box that runs the Squad fleet. Adapt to
# your hardware/provider. The fleet itself lives in squad-fleet.nix, imported
# here. Replace the SSH key, hostname, and review the bootloader/network bits
# for your machine (these defaults suit a typical bare-metal/VPS host).

{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix   # generated by nixos-generate-config on YOUR box
    ./squad-fleet.nix              # the fleet (see that file)
  ];

  # ── Boot ────────────────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 10;   # cap stored generations
  boot.loader.efi.canTouchEfiVariables = true;

  # ── Networking ────────────────────────────────────────────────────────────
  networking.hostName = "squad";          # CHANGE_ME
  networking.useDHCP = lib.mkDefault true;
  # The fleet module opens each instance's game/query/rcon/beacon ports itself.

  # ── SSH (key-only) ──────────────────────────────────────────────────────
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
    settings.PermitRootLogin = "prohibit-password";
  };
  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 CHANGE_ME_YOUR_PUBLIC_KEY user@host"
  ];

  # ── Misc ──────────────────────────────────────────────────────────────────
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  time.timeZone = "UTC";
  system.stateVersion = "25.11";   # set to the release you installed; don't bump casually
}
